### ISSUE TITLE
ImportError 

### ISSUE THREAD

**Issue by samlcharreyron** [srgblnch/python-pylon#10]
I built the module using pylon 4 on Ubuntu 14.04 without problems. When I try to load the module however I get the following error

`
~/src/python-pylon/build/lib.linux-x86_64-2.7$ python -c "import pylon"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: ./pylon.so: undefined symbol: _ZTIN5Pylon9CInfoBaseE
` 

Could it be that the the build module isn't linking the pylon library? See below:

`
~/src/python-pylon/build/lib.linux-x86_64-2.7$ ldd pylon.so 
    linux-vdso.so.1 =>  (0x00007ffe61577000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f77a02a2000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f77a008c000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f779fe6e000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f779faa9000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f779f7a3000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f77a07f5000)
`

**Comment by blazterb** [comment]
Same problem. Build with pylon 5 on Ubuntu 16.04. Same error

**Comment by blazterb** [comment]
Hi, followed second branch. Used changes made there in setup.py. Rebuilt. Installed python-libxml2. It works for me

**Comment by samlcharreyron** [comment]
Still not working for me. I get the following error:

['ImportError: /home/local/.pyxbld/lib.linux-x86_64-2.7/pylon/**init**.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE\n']

Could I see your fork to see what changes you made?

**Comment by blazterb** [comment]
Did you run [source env.sh pylon 4] ?

**Comment by blazterb** [comment]
https://github.com/blazterb/python-pylon
this is the link

**Comment by samlcharreyron** [comment]
yes I did. Thanks I'll check it out.

**Comment by samlcharreyron** [comment]
Ok great, hardcoding the libraries worked. I modified your version to work for pylon 4.
