### ISSUE TITLE
Import fails with "undefined symbol: _ZTIN5Pylon9CInfoBaseE"

### ISSUE THREAD

**Issue by hgmeyer** [srgblnch/python-pylon#12]
Hey,
I built python-pylon for Pylon 5. After adding `pylon.so` to my python path and sourcing the environment variables like this:

```
~/src $ export PYTHONPATH="${PYTHONPATH}:/home/hanno/src/python-pylon/build/lib.linux-x86_64-2.7/"
~/src $ source python-pylon/env.sh
```

Importing pylon fails:

```
~/src $ ipython
[...]
In [1]: import pylon
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d1fefb2fb6dd> in <module>()
----> 1 import pylon

ImportError: /home/hanno/src/python-pylon/build/lib.linux-x86_64-2.7/pylon.so: undefined symbol: _ZTIN5Pylon9CInfoBaseE
```

Any idea how to solve this issue?

**Comment by mypolopony** [comment]
I can confirm this same issue with Pylon 5, Python 2.7, Ubuntu 16.04

**Comment by abhishekpratapa** [comment]
Same issue

**Comment by gmiller-whus** [comment]
I'm getting the same error, using a slightly different set of commands.

python

> > > import ctypes
> > > import pylon
> > > pplib = ctypes.cdll.LoadLibrary( './build/lib.linux-x86_64-2.7/pylon.so' )
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.7/ctypes/**init**.py", line 443, in LoadLibrary
> > >     return self._dlltype(name)
> > >   File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in **init**
> > >     self._handle = _dlopen(self._name, mode)
> > > OSError: ./build/lib.linux-x86_64-2.7/pylon.so: undefined symbol: _ZTIN5Pylon9CInfoBaseE

**Comment by uwe12** [comment]
Hi,

I experience the same problem as the thread starter. Translated from the symbols, the missing symbol reads: `typeinfo for Pylon::CInfoBase`.

@srgblnch did you forget to commit a file for the `CInfoBase` class? :)

**Comment by ax3l** [comment]
It looks like `Pylon::CInfoBase` is actually a class of the original Basler Pylon SDK and we just forgot to link it into the `pylon.so` python API.

**Comment by ax3l** [comment]
@srgblnch uh, I actually did not try to fix that problem. Do you have a solution how to fix the missing symbol?

**Comment by srgblnch** [comment]
I couldn't reproduce this exact missing symbol. But my experience when this errors occur is that, somehow, a different source was used to compile than execute. In link time, some function was there but in execution it is missing.

My suggestion is to be sure that the same pylon.so can be found in both cases. But usually, testing something like this project, one is even using the same terminal with the same variables loaded. In that case, I feel I need to reproduce the problem to understand what happen.

**Comment by souhhano** [comment]
Hi,

same issue with an ubuntu 16.04 and pylon 5. Is there any way to link the missing library and do you guys have any idea with .so is it? 

Thanks.
