### ISSUE TITLE
import error _ZN8CppINode12isDeprecatedEv

### ISSUE THREAD

**Issue by qwe2tz** [srgblnch/python-pylon#13]
When trying to import pylon I get the following error:

ImportError: /usr/local/lib/python2.7/dist-packages/pylon.so: undefined symbol: _ZN8CppINode12isDeprecatedEv

I've searched around a bit and didn't find a solution.

**Comment by srgblnch** [comment]
By the way this is (extremely) very old, there was another similar [issue](https://github.com/srgblnch/python-pylon/issues/12) with a runtime error undefined symbol. 

Is the problem still there? (Are you still interested on this project?) May the other issue be related?
