### ISSUE TITLE
Make code GigE agnostic

### ISSUE THREAD

**Issue by mabl** [srgblnch/python-pylon#4]
I have a USB3 camera, so having the code GigE agnostic is a good idea. I've gotten the code to build with pylon 5 and my USB3 camera with the changes in my mabl/pylon5 branch.

```
In [1]: import pylon

In [2]: factory = pylon.Factory()
MainThread      DEBUG   2016-01-11 17:15:05.017226      Factory()       Called __init__()
GetDeviceDiscoveryInfo: bFunctionClass = 14, bFunctionSubClass = 3, bFunctionProtocol = 0. Device is not an U3V device.
140298324981504 DEBUG   2016-01-11 17:15:05     CppFactory()    Found 1 within the transport layer BaslerGigE
140298324981504 DEBUG   2016-01-11 17:15:05     CppFactory()    Found a acA2040-90um Camera, with serial number 21771378
MainThread      DEBUG   2016-01-11 17:15:05.275780      Factory()       __init__() done

In [3]: factory.getCameraBySerialNumber(21771378)
MainThread      DEBUG   2016-01-11 17:15:09.096831      Factory()       Preparing the camera with the serial number 21771378
MainThread      DEBUG   2016-01-11 17:15:09.097030      Factory()       Building instance for the camera with the serial number 21771378
MainThread      DEBUG   2016-01-11 17:15:09.097103      Camera()        Void Camera Object build, but it doesn't link with an specific camera
140298324981504 DEBUG   2016-01-11 17:15:09     CppFactory()    Creating a Camera object from the information of the camera with the serial number 21771378
140298324981504 DEBUG   2016-01-11 17:15:09     CppFactory()    Creating CInstantCamera object
GetDeviceDiscoveryInfo: bFunctionClass = 14, bFunctionSubClass = 3, bFunctionProtocol = 0. Device is not an U3V device.
140298324981504 DEBUG   2016-01-11 17:15:09     CppFactory()    Created CInstantCamera object
140298324981504 DEBUG   2016-01-11 17:15:09     CppFactory()    Getting the IPylonDevice object
MainThread      DEBUG   2016-01-11 17:15:09.153458      Camera()        New name: Camera(21771378)
Out[3]: <pylon.Camera at 0x7f99b8f416c0>

In [4]: camera = factory.getCameraBySerialNumber(21771378)
MainThread      DEBUG   2016-01-11 17:15:20.586423      Factory()       Preparing the camera with the serial number 21771378
MainThread      DEBUG   2016-01-11 17:15:20.586788      Factory()       Camera with the serial number 21771378 already instanciated

In [5]: camera
Out[5]: <pylon.Camera at 0x7f99b8f416c0>

In [6]: 
Do you really want to exit ([y]/n)? 
Dummy-1 DEBUG   2016-01-11 17:27:17.573848      Factory()       Called __dealloc__()
Dummy-1 DEBUG   2016-01-11 17:27:17.574153      Factory()       Called __del__()
Dummy-1 DEBUG   2016-01-11 17:27:17.574237      Factory()       Clean lists: loop 0 (1,1,1,1,1,1)
Dummy-1 DEBUG   2016-01-11 17:27:17.574302      Factory()       Removing cameraLst object 21771378
Dummy-1 DEBUG   2016-01-11 17:27:17.574378      Factory()       Removing cameraModels key acA2040-90um: object [21771378 (acA2040-90um)]
Dummy-1 DEBUG   2016-01-11 17:27:17.574435      Factory()       Removing acA2040-90um object 21771378
Dummy-1 DEBUG   2016-01-11 17:27:17.574492      Factory()       Removing serialDct key 21771378: object 21771378
Dummy-1 DEBUG   2016-01-11 17:27:17.574549      Factory()       Removing ipDct key N/A: object 21771378
Dummy-1 DEBUG   2016-01-11 17:27:17.574616      Factory()       Removing macDct key N/A: object 21771378
Dummy-1 DEBUG   2016-01-11 17:27:17.574708      Factory()       Removing instance key 21771378: object <pylon.Camera object at 0x7f99b8f416c0>
Dummy-1 DEBUG   2016-01-11 17:27:17.574775      Factory()       Clean structures finish ok
Dummy-1 DEBUG   2016-01-11 17:27:17.574820      Factory()       Releasing the Transport Layer
Dummy-1 DEBUG   2016-01-11 17:27:17.574853      Factory()       Remove the factory
Dummy-1 DEBUG   2016-01-11 17:27:17.577798      Factory()       Factory deletion complete
Dummy-1 DEBUG   2016-01-11 17:27:17.577907      Factory()       __del__() done
Dummy-1 DEBUG   2016-01-11 17:27:17.577956      Factory()       __dealloc__() done

```

**Comment by maxlklaxl** [comment]
did you delete your branch? I don't find it

**Comment by mabl** [comment]
Yes by accident at home... I'll push it when I come back to work tomorrow. I've also fixed some pointer troubles in the Camera creation. This might be the issue @srgblnch  was facing earlier.

**Comment by maxlklaxl** [comment]
it builds and imports now fine with your [changes](https://github.com/srgblnch/python-pylon/issues/3), will test it tomorrow with a GigE cam

**Comment by mabl** [comment]
Wait for the the branch to appear tomorrow morning. There are some more fixes, namely transport agnostic camera handling and fixes for camera creation (there was some double pointer weirdness). Furthermore it will build against Pylon 5 using Python 2.7 and 3 (I tested 3.5).

I think its also a good idea to change the parameter/function naming scheme to match PEP8. Simple image graping and generic camera parameter handling should also be easy to add.  However, I'm unsure if I can further contribute due to the GPL licence of the library... I've asked @srgblnch if he'd be willing to re-licence to at least LGPL (or even Apache/MIT?).

**Comment by mabl** [comment]
Branch should be there again: https://github.com/mabl/python-pylon/tree/pylon5

**Comment by srgblnch** [comment]
I'm glad to see you working/developing/contributing. That's very nice because I've thought more in people that some day may use it, but this is even better. I like to mention that this project is not even yet in a pre-alpha stage. This has been a discontinuous time project to be start more like a prove of concept.
We may start an specific issue about the licencing.

**Comment by maxlklaxl** [comment]
tested it with a GigE

``` bash
Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylon
>>> pylon.version_python_pylon_string()
'0.0.0-0'

>>> pylon.version_pylon_API_string()
'5.0.1-6388'

>>> factory = pylon.Factory()
MainThread  DEBUG   2016-01-12 19:09:56.551919  Factory()   Called __init__()
GetDeviceDiscoveryInfo: bFunctionClass = 14, bFunctionSubClass = 3, bFunctionProtocol = 0. Device is not an U3V device.
140339635685120 DEBUG   2016-01-12 19:09:56 CppFactory()    Found 1 cameras 
140339635685120 DEBUG   2016-01-12 19:09:56 CppFactory()    Found a acA640-120gm Camera, with serial number 21625707    
(21625707, <type 'int'>)
MainThread  DEBUG   2016-01-12 19:09:56.814889  Factory()   __init__() done

>>> factory.nCameras
1

>>> factory.macList
[u'00305318CE6B']

>>> factory.ipList
[u'192.168.1.12']

>>> factory.camerasList
[21625707 (acA640-120gm)]

>>> factory.cameraModels
[u'acA640-120gm']

>>> cam = factory.getCameraBySerialNumber(21625707)
MainThread  DEBUG   2016-01-12 19:11:27.174648  Factory()   Preparing the camera with the serial number 21625707
MainThread  DEBUG   2016-01-12 19:11:27.174817  Factory()   Building instance for the camera with the serial number 21625707
MainThread  DEBUG   2016-01-12 19:11:27.174883  Camera()    Void Camera Object build, but it doesn t link with an specific camera
140339635685120 DEBUG   2016-01-12 19:11:27 CppFactory()    Creating a Camera object from the information of the camera with the serial number 21625707 
140339635685120 DEBUG   2016-01-12 19:11:27 CppFactory()    Creating CInstantCamera object  
140339635685120 DEBUG   2016-01-12 19:11:27 CppFactory()    Created CInstantCamera object   
140339635685120 DEBUG   2016-01-12 19:11:27 CppFactory()    Getting the IPylonDevice object 
MainThread  DEBUG   2016-01-12 19:11:27.282301  Camera()    New name: Camera(21625707)

>>> dir(cam)
['__class__', '__del__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__pyx_vtable__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_debug', '_error', '_info', '_print', '_threadId', '_type', '_warning']
```

**Comment by srgblnch** [comment]
I'm reading the changes on this branch "pylon5". I like to take many of the changes in the master branch, specially the ones that fixes the issue to have the IPylonDevice object well made and capable to have access to the camera.

In this master branch I did some modifications to suport from pylon 2 to 5 (I still need to make it work in pylon 2) correctly as well as the 32 and 64 arch (perhaps some day we may work in arm, but not yet my case). I also like to have the code python 2 and 3 compatible.

Ah, the license has been already changed to LGPLv3+.

**Comment by mabl** [comment]
Sure. Feel free to cherry pick them / rewrite them yourself so they match your code.  My pylon5 is currently just a playing ground for me. (You might have seen I ripped out the logger partially... but somehow I still don't like it :-D have to map the cpp Logger to the python logging module too)

**Comment by srgblnch** [comment]
I've take the modifications that looks to fix the issue I had with the CBaslerGigECamera (replace by CInstantCamera) and other changes in the TransportLayer construction. Also I've pushed the environment changes. This doesn't work with pylon 2, but I'm the only interested then I'll check it later.

We may have to reorganize the issues open and talk about a communication system between developers.

**Comment by srgblnch** [comment]
I think the code in the master branch is now "GigE agnostic". If I understand correctly this means that not only gige (basler) cameras are supported and others can be used like the usb example. Can be this confirmed?

By now the support for pylon2 is broken, but I like to know how this works in newer releases. In pylon 3 it looks ok, but I get a segmentation fault in 4 and 5.

**Comment by mabl** [comment]
Hi @srgblnch, I haven't tested latest master, but it worked for USB as well. Fields like ethernet address etc return the 'N/A' string in that case.

**Comment by srgblnch** [comment]
The CppDevInfo class may need to be subclissified based on the factory. The ethernet attributes should not be present in usb, and with usb other attributes should be shown.

**Comment by mabl** [comment]
the cython code could also just raise an Attribute Error or so. (or just return None)

**Comment by srgblnch** [comment]
I've just made a push with a DevInfo subclassing to distinguish between cameras GigE and others (not yet, but can be made a subclass for usb ones). Then the network information on a DevInfo will only be present when it have sense.
