### ISSUE TITLE
Alternative Pylon wrapping

### ISSUE THREAD

**Issue by mabl** [srgblnch/python-pylon#6]
Hi srgblnch,

yesterday I felt an urge to try the Basler cam with Python again. I've hence tried my own hand in trying to wrap the Basler Pylon library. My approach differs such, that no intermediate C++ classes are used but rather the Pylon Classes are directly used inside the cython wrapper code.

In addition, the code tries to autoconfigure itself for pylon by using the /opt/pylon5/bin/pylon-config tool.

If you want to have a look check out https://github.com/mabl/PyPylon. 

I got so far, that I can get camera images:

``` python
import pypylon
import matplotlib.pyplot as plt


print('Build against pylon library version:', pypylon.pylon_version.version)

available_cameras = pypylon.factory.find_devices()
print('Available cameras are ', available_cameras)

# Grep the first one and create a camera for it
cam = pypylon.factory.create_device(available_cameras[0])

# We can still get information of the camera back
# print(cam.device_info)

# Open camera and grep some images
cam.open()
for image in cam.grap_images(5):
    plt.imshow(image)
    plt.show()
```

**Comment by srgblnch** [comment]
Sorry for not looking on the issues of this project. Your approach seems better as it is simpler, works and you develop faster. Sometime ago I've pointed your project in the readme.
