### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by aamirabbasi89** [srgblnch/python-pylon#8]
Running into this problem,

Environment set for Pylon 5 arch32.
Not found Pylon installed in /pylon5
At least it is necessary to have a symbolic link in /opt

I have tried to changed the PYLON_BASE to the location of pylon software suite in env.sh file but still it is giving me this error. 

The location of my Pylon 5 is C:/Basler/Pylon 5
I am using Python 3.5.1 on a windows 8.1 computer.

**Comment by srgblnch** [comment]
Sorry but I haven't read the issues of this project since now. This toy-project I've only used linux for it. Did you find how to make it work in windows?
