### ISSUE TITLE
cameraList

### ISSUE THREAD

**Issue by aalj011** [srgblnch/python-pylon#9]
i can import pylon into python and when i create "factory = pylon.Factory()" my camera is found (over GigE) and is part of the list (see below image)
![capture](https://cloud.githubusercontent.com/assets/11814116/16180091/c723d61a-36ce-11e6-8d3a-a20de042b385.JPG)

However when i call any of the other functions e.g factory.camerasList i get an empty array "[ ]"
Thoughts?

Thanks

**Comment by srgblnch** [comment]
I didn't check the issues of this project before, sorry. The process of the factory, when cameras are found are stored in a list from where later is populated the information on the camerasList property. I've no idea what when wrong.
